---
- hosts: localhost
  become: true
  connection: local

  tasks:
    - name: Update APK cache
      apk:
        update_cache: yes

    - name: Installing Redis
      apk:
        name: "redis"
        state: "present"

    - name: Settings values in Redis configuration (1)
      replace:
        dest: "/etc/redis.conf"
        regexp: "^{{ item.regex }}"
        replace: "{{ item.replace }}"            
      with_items:
        - regex: 'bind 127.0.0.1'
          replace: 'bind 0.0.0.0'
        - regex: 'daemonize yes' 
          replace: 'daemonize no'         